# Generated by Django 6.0.6 on 2026-06-24 12:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('top_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_snapshots_as_top_product', to='catalog.product')),
                ('top_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_snapshots_as_top_vendor', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_a_date_ca2b97_idx'), models.Index(fields=['top_vendor', 'date'], name='analytics_a_top_ven_e6fb43_idx'), models.Index(fields=['top_product', 'date'], name='analytics_a_top_pro_728838_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_revenue__gte', 0)), name='analytics_snapshot_total_revenue_nonnegative'), models.CheckConstraint(condition=models.Q(('total_orders__gte', 0)), name='analytics_snapshot_total_orders_nonnegative'), models.CheckConstraint(condition=models.Q(('new_customers__gte', 0)), name='analytics_snapshot_new_customers_nonnegative')],
            },
        ),
    ]
