# Generated by Django 6.0.6 on 2026-06-17 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('track_inventory', models.BooleanField(db_index=True, default=True)),
                ('allow_backorder', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='catalog.product')),
                ('variant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_record', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['product__name', 'variant__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('before_on_hand', models.PositiveIntegerField()),
                ('after_on_hand', models.PositiveIntegerField()),
                ('before_reserved', models.PositiveIntegerField()),
                ('after_reserved', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['product', 'track_inventory'], name='inventory_i_product_89071d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['variant', 'track_inventory'], name='inventory_i_variant_b71932_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['quantity_on_hand'], name='inventory_i_quantit_5f1310_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryrecord',
            index=models.Index(fields=['quantity_reserved'], name='inventory_i_quantit_e85a3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('product',), name='inventory_one_product_level_record'),
        ),
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inventory_quantity_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='inventory_quantity_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryrecord',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='inventory_low_stock_threshold_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_record', 'created_at'], name='inventory_s_invento_d227f7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_stock_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('before_on_hand__gte', 0)), name='inventory_before_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('after_on_hand__gte', 0)), name='inventory_after_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('before_reserved__gte', 0)), name='inventory_before_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('after_reserved__gte', 0)), name='inventory_after_reserved_non_negative'),
        ),
    ]
