version: '3.9'

services:

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  django:
    build: .
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    restart: always
    command: celery -A config worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    restart: always
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
