# Generated by Django 6.0.6 on 2026-06-22 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WELCOME', 'Welcome'), ('ORDER_CREATED', 'Order Created'), ('PAYMENT_SUCCESS', 'Payment Success'), ('VENDOR_APPROVED', 'Vendor Approved'), ('VENDOR_NEW_ORDER', 'Vendor New Order'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('REVIEW_REMINDER', 'Review Reminder')], db_index=True, max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In App')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'channel'], name='notificatio_user_id_af98f8_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx'), models.Index(fields=['channel', 'created_at'], name='notificatio_channel_428142_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('channel__in', ['EMAIL', 'SMS', 'IN_APP'])), name='notifications_valid_channel'), models.CheckConstraint(condition=models.Q(('type__in', ['WELCOME', 'ORDER_CREATED', 'PAYMENT_SUCCESS', 'VENDOR_APPROVED', 'VENDOR_NEW_ORDER', 'LOW_STOCK_ALERT', 'REVIEW_REMINDER'])), name='notifications_valid_type')],
            },
        ),
    ]
